# Last updated 2016-04-08
development:
  adapter: postgresql
  encoding: unicode
  database: expense_sandbox_development
  pool: 5
  username: expense_admin
  password: 5GLqs_x2xnPS

test:
  adapter: postgresql
  encoding: unicode
  database: expense_sandbox_test
  pool: 5
  username: expense_admin
  password: 5GLqs_x2xnPS