# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05a9b000c8c3b29a5d1530a29abe0d61f9ff69595ea5cb4d271609f42239d356ab46a1e99170ca7722f0342813eb56f8680decf46219f6d5c8d6a892e5ea1953

test:
  secret_key_base: d9c4741b16b0c7ebf92c8b77e6870bd0b6c8852e6115a249468a8bd1bcc2c771ea686f02c6e87088e902ca0003bc1709b35ae56755295a57eb3ab38345e68897

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
